#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")
trigger: none
pool:
 name: AdminNico-AP
variables:
 buildConfiguration: 'Release'


steps:
  - checkout: self
    clean: true
    fetchDepth: 1

  - script: |
      echo Agent: $(Agent.Name)
      where java
      java -version
    displayName: "Sanity: agent & java"

  - task: UseDotNet@2
    displayName: "Install .NET SDK 6.x (fallback)"
    inputs:
      packageType: 'sdk'
      version: '6.x'

  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'AppSecNico-SQCon'
      scannerMode: 'MSBuild'
      projectKey: 'squ_2d280969690c7d49f39a012795a19f3892d6301c'
      projectName: 'AppSecNico'

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: '**/*.sln'
      feedsToUse: 'select'
        
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: '**/*.sln'
    
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: 'test'
      projects: 'tests/UnitTests/*.csproj'
    
  - task: DotNetCoreCLI@2
    displayName: Integration Tests
    inputs:
      command: 'test'
      projects: 'tests/IntegrationTests/*.csproj'
    
  - task: DotNetCoreCLI@2
    displayName: Functional Tests
    inputs:
      command: 'test'
      projects: 'tests/FunctionalTests/*.csproj'
    
  - task: SonarQubeAnalyze@5

  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'













     


