#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")
trigger:
   branches:
     include:
     - main
   paths:
     include:
     - src/web/*

resources:
  repositories:
    - repository: self
      trigger: none

stages:
- stage: Build
  displayName: Build .Net Core Solution
  jobs:
  - job: Build
    pool:
      name: AdminNico-AP
      demands: Agent.Name -equals AdminNico
      
    steps:


    #- task: SonarQubePrepare@7
    #  inputs:
     #   SonarQube: 'AppSecNico-SQCon'
      #  scannerMode: 'dotnet'
      #  projectKey: 'squ_2d280969690c7d49f39a012795a19f3892d6301c'
      #  projectName: 'AppSecNico'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.sln'
        feedsToUse: 'select'
        
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.sln'
    
   # - task: DotNetCoreCLI@2
    #  displayName: Test
     # inputs:
      #  command: 'test'
       # projects: 'tests/UnitTests/*.csproj'
    
   # - task: DotNetCoreCLI@2
    #  displayName: Integration Tests
     # inputs:
      #  command: 'test'
       # projects: 'tests/IntegrationTests/*.csproj'
    
  #  - task: DotNetCoreCLI@2
    #  displayName: Functional Tests
     # inputs:
      #  command: 'test'
       # projects: 'tests/FunctionalTests/*.csproj'

    #- task: SonarQubeAnalyze@7
      #inputs:
        #jdkversion: 'JAVA_HOME_21_X64'
        
      
    #- task: SonarQubePublish@7
      #inputs:
       # pollingTimeoutSec: '300'
  
    - task: CmdLine@2
      displayName: Dependency Track Cyclone DX
      inputs:
        script: |
          dotnet tool install --global CycloneDX
          dotnet-CycloneDX eShopOnWeb.sln -o ../TestResults/
    - task: upload-bom-dtrack-task@1
      displayName: Upload BOM to Dependency Track
      inputs:
        dtrackProjName: 'AppSecNico'
        dtrackProjVersion: '1.0'
        dtrackProjAutoCreate: true
        bomFilePath: '../TestResults/bom.xml'
        dtrackAPIKey: 'odt_Ro82liy8_BJTkUcPzjTKVC7SOkqHJasJwF4B9dghi'
        dtrackURI: 'http://dependencytrack.southcentralus.cloudapp.azure.com:8080'


